language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - "sudo apt-get -qq update"
# Dependencies for LXML
  - "sudo apt-get install -y -qq libxml2-dev libxslt-dev python-dev"

install:
  - pip install .
script:
  - python -m unittest discover -s FlexTransform/FlexTransform/test/ -p "To*Tests.py"
git:
  depth: 3