language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
before_install:
- "sudo apt-get -qq update"
- "sudo apt-get install -y -qq libxml2-dev libxslt-dev python-dev"
install:
- "pip install ."
script:
- "nosetests"
deploy:
  provider: "pypi"
  user: "anl-cyberscience"
  password:
    secure: HgtKQyGDlTHrhlaH+Cr6F56MTNJ2lwkAjKod7ifUy+dBqZ/FHHqPmLgAbGTlIG9si0dvG1IgOz8de/Vr1+AO3w/J18zmop5xPyv1PreqOCSwbRWK76dJG4vsUB7nW+eRwg29YcPVUmtw+z6qHYEAiR6/GQNKi3ubw5RRO4Oily3QxkOr48pGStiW8f8hHGI8mgLw16saVxAV+yFiaXFikmUHBro1G33W78ZOJhpgxEAMXzPCZHeIepnDZNDmCERX7YZdy9q5uV07WmRqEjLSNpfvdyJSS2T66ZKZ7mcB/2M3sFtz7t5datqAudlNuy9o5JAsPavkxJNz0u6A0V8Ee7ETeRwDKhhuhgBtVStEZHNas7XZaiJzM4TbFTJvgL7lU5mPXzo3cxjuSdlz8Px7Heq3jp5vdE94locYEjd1iQ8KFMIxjQIA15WHKYcDGy9iG4M7iQl7Up3JCCQC+Dsj5v1eHm3YITDd7P8g2c9/xeGcvpWx6zYaukSS2oBuBEuwfQz0JCuVSZkajWg9IETb6iQFml+IZg8uoLP+jOKjDTY4S4a/jiRqHa132q6+bZ5QQWCl8b+fyX+VcPLIAl8BtA/bwQ6cJW1Gni69RSjLxbGe5neUsjfZL4fKO+QnunfxDviRnt4lBqG4Cce2n2YNW40DydaGRXfDR+gUqhDO3IM=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
notifications:
  slack:
    secure: i2h5/x8NkHYjIxqj1znDK9UkQpjT28aSrIG6YNInURb963+oQV27tRclDDfG+VBigRNF3TvFFApQhzDt/che1W2MsQdVcC8uAL+Lin8IetSV9A3iQL1P3g4NuG6SDPUoWydr1cY/3ONNkZsXms3pSJTrRm9kLYGPB6X7u3TvBgluzdEhxaafUfZgNcV9tPBx1wkzu4/61Qz8Ff1SftIrIitpc1Njytpibjlxl6qo4tlJRacBcu0AagVRtbi1COb5gbL4jdQFqzt1D7BP6ltBLDGEreb3Eucd/s2j8ONwKvem26g9BQCLHx/xD9hoU4rBZ1i8SomkLUZBAFl3avKq6WvYMmFaKe3pVgiFEAPwKNRxoZYLHOGTBgxyKQi1Nuv/iM4MZx15JAQERL4I+Q7BMBRbC+Om3Uv1xAcKfX5CsOyAUdWc6RjwU0XQunqxCQvO/Nvjz5ZMLhU1W7fPUYxU21ye3PgNZq9hcQRWsFDlPPmYM4JmbKgtoNo+vVGUoOvEkG0WId4bJ1W9PXkvyMa4+1c6Gs3tWq78fre8vK/LFcxbRxIufJ5rxUne6TgdQ5Y70gjJgOiqlz43XMmPlmo2/ORLYaN/IyoBZMP1UKAJRYlMEeOPmyWKOoG4gOnCW5yXKlcmuVKDoKdLybBofgRKJCRM7/QKNLhvNSVDvr/J5GU=
